pool:
  vmImage: 'windows-2022'

steps:

- task: UseDotNet@2
  displayName: 'Install .NET SDK'
  inputs:
    version: 6.0.100
    performMultiLevelLookup: true

- task: VSBuild@1
  displayName: Build
  inputs:
    configuration: 'Release'
    msbuildArgs: '/restore'

- task: VSTest@2
  displayName: Test
  inputs:
    configuration: 'Release'
    otherConsoleOptions: '/Framework:.NETCoreApp,Version=v6.0 /Platform:x64'